version: "3.7"

services:
  api:
    image: lucasalmdsilva/catalog_api:latest
    pull_policy: always
    hostname: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - AWS_REGION=
      - AWS_SNS_TOPIC_ARN=
      - AWS_CREDENTIALS_KEY_ACCESS=
      - AWS_CREDENTIALS_KEY_SECRET=
  consumer:
    image: lucasalmdsilva/catalog_consumer:latest
    pull_policy: always
    hostname: consumer
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - AWS_REGION=
      - AWS_S3_BUCKET_NAME=
      - AWS_SQS_NAME=
      - AWS_CREDENTIALS_KEY_ACCESS=
      - AWS_CREDENTIALS_KEY_SECRET=
  db:
    image: mongo:4.4.6
    hostname: db
    ports:
      - "27017:27017"
